# Generated by Django 4.2 on 2024-11-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0005_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
